function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          Welcome to Tanqory
        </h1>
        <p className="text-gray-600">
          Your website is being generated by AI...
        </p>
      </div>
    </div>
  );
}

export default App;
